# 下面是系統配置
development:
  # web_name: 测试-“绿色梦想，青春六月”---西湖花圃健步走活动
  # address: 杭州花圃
  # time: 2019年6月1日 09:30--12:00
  web_name: 宜康工会夏季观影活动
  address: '时代联合影院Gmax厅&星伦多海鲜自助'
  time: '2023年8月11日/2023年8月18日 13:30 - 18:30'
production:
  web_name: 车辆信息登记
  address: '公司楼下或园区'
  time: '2023年10月1日至2024年3月31/2024年9月30日'
