# 下面是系統配置
development:
  web_name: 测试-“绿色梦想，青春六月”---西湖花圃健步走活动
  address: 杭州花圃
  time: 2019年6月1日 09:30--12:00
production:
  web_name: “绿色梦想，青春六月”---西湖花圃健步走活动
  address: 杭州花圃
  time: 2019年6月1日 09:30--12:00
