# 下面是系統配置
development:
  web_name: 测试-abcam 20 years anniversary celebration
  address: Open Office
  time: 2018年12月6日 12:15--12:55
production:
  web_name: 正式-abcam 20 years anniversary celebration
  address: Open Office
  time: 2018年12月6日 12:15--12:55
