# 下面是系統配置
development:
  web_name: abcam 联谊活动
  sub_title: 长路携手，我想和你在一起
  address: 上城区机械功能区党群人才服务中心
  time: 2021年01月10日(周天) 13:30--17:30
production:
  web_name: abcam 产品查询
  sub_title: 长路携手，我想和你在一起
  address: 上城区机械功能区党群人才服务中心
  time: 2021年01月10日(周天) 13:30--17:30
