# 下面是系統配置
development:
  web_name: 测试-“绿色梦想，青春六月”---西湖花圃健步走活动
  address: 杭州花圃
  time: 2019年6月1日 09:30--12:00
production:
  web_name: 2023年abcam旅游活动
  address: 无锡拈花湾，宁波象山，广东汕头，云南大沙溪，泰国曼芭，蓝梦巴厘
  time: 2023年04月至06月
